people_list = [
    "Barack Obama",
    "Bill Gates",
    "Steve Jobs",
    "Mark Zuckerberg",
    "Elon Musk",
    "Jeff Bezos",
    "Oprah Winfrey",
    "J.K. Rowling",
    "Stephen King",
    "George R.R. Martin",
    "Neil Gaiman",
    "Salman Rushdie",
    "Haruki Murakami",
    "Dan Brown",
    "John Green",
    "Malala Yousafzai",
    "Greta Thunberg",
    "Emma Watson",
    "Leonardo DiCaprio",
    "Tom Hanks",
    "Meryl Streep",
    "Denzel Washington",
    "Jennifer Lawrence",
    "Robert Downey Jr.",
    "Scarlett Johansson",
    "Beyoncé",
    "Taylor Swift",
    "Ed Sheeran",
    "Adele",
    "Lady Gaga",
    "Drake",
    "Eminem",
    "Kanye West",
    "Rihanna",
    "Bruno Mars",
    "LeBron James",
    "Cristiano Ronaldo",
    "Lionel Messi",
    "Serena Williams",
    "Usain Bolt",
    "Michael Phelps",
    "Roger Federer",
    "Tiger Woods",
    "Simone Biles",
    "Nadia Comaneci",
    "Stephen Hawking",
    "Neil deGrasse Tyson",
    "Jane Goodall",
    "Michio Kaku",
    "Brian Cox",
    "Satya Nadella",
    "Sundar Pichai",
    "Jack Ma",
    "Richard Branson",
    "Arianna Huffington",
    "Sheryl Sandberg",
    "Marissa Mayer",
    "Indra Nooyi",
    "Mary Barra",
    "Ursula Burns",
    "Tim Cook",
    "Reed Hastings",
    "Bob Iger",
    "Howard Schultz",
    "Jack Dorsey",
    "Larry Page",
    "Sergey Brin",
    "Jimmy Wales",
    "Larry Ellison",
    "Michael Dell",
    "Shigeru Miyamoto",
    "Satoru Iwata",
    "George Lucas",
    "Steven Spielberg",
    "James Cameron",
    "Quentin Tarantino",
    "Christopher Nolan",
    "Peter Jackson",
    "Spike Lee",
    "Wes Anderson",
    "Sofia Coppola",
    "Kathryn Bigelow",
    "J.J. Abrams",
    "Ava DuVernay",
    "Jordan Peele",
    "Greta Gerwig",
    "Damien Chazelle",
    "Lin-Manuel Miranda",
    "Banksy",
    "Ai Weiwei",
    "Jeff Koons",
    "Damien Hirst",
    "Yayoi Kusama",
    "Marina Abramović",
    "Olafur Eliasson",
    "Takashi Murakami",
    "Cindy Sherman",
    "David Hockney",
    "Anish Kapoor",
    "Kara Walker",
    "Shepard Fairey",
    "JR",
    "Emma González",
    "Boyan Slat",
    "Gitanjali Rao",
    "Xiuhtezcatl Martinez",
    "Jazz Jennings",
    "Joshua Wong",
    "Marley Dias",
    "Thandiwe Abdullah",
    "Jacinda Ardern",
    "Emmanuel Macron",
    "Justin Trudeau",
    "Volodymyr Zelenskyy",
    "Sanna Marin",
    "Alexandria Ocasio-Cortez",
    "Ilhan Omar",
    "Rashida Tlaib",
    "Pete Buttigieg",
    "Stacey Abrams",
    "Cory Booker",
    "Kamala Harris",
    "Beto O'Rourke",
    "Andrew Yang",
    "Tulsi Gabbard",
    "Edward Snowden",
    "Julian Assange",
    "Chelsea Manning",
    "Mark Ruffalo",
    "Angelina Jolie",
    "George Clooney",
    "Bono",
    "Shakira",
    "Pharrell Williams",
    "John Legend",
    "Michelle Obama",
    "Hillary Clinton",
    "Angela Merkel",
    "Theresa May",
    "Nicola Sturgeon",
    "Ursula von der Leyen",
    "Christine Lagarde",
    "Janet Yellen",
    "Ruth Bader Ginsburg",
    "Sonia Sotomayor",
    "Elena Kagan",
    "Ketanji Brown Jackson",
    "Condoleezza Rice",
    "Madeleine Albright",
    "Colin Powell",
    "John Kerry",
    "Al Gore",
    "Jimmy Carter",
    "Joe Biden",
    "Donald Trump",
    "Bernie Sanders",
    "Elizabeth Warren",
    "Mitt Romney",
    "John McCain",
    "Sarah Palin",
    "Nancy Pelosi",
    "Mitch McConnell",
    "Chuck Schumer",
    "Paul Ryan",
    "John Boehner",
    "Ted Cruz",
    "Marco Rubio",
    "Rand Paul",
    "Nikki Haley",
    "Mike Pence",
    "Chris Christie",
    "Rudy Giuliani",
    "Michael Bloomberg",
    "Cory Booker",
    "Kamala Harris",
    "Amy Klobuchar",
    "Kirsten Gillibrand",
    "Julian Castro",
    "Tim Kaine",
    "Gavin Newsom",
    "Gretchen Whitmer",
    "Ron DeSantis",
    "Greg Abbott",
    "Larry Hogan",
    "Charlie Baker",
    "Bill de Blasio",
    "Eric Adams",
    "Lori Lightfoot",
    "Eric Garcetti",
    "Keisha Lance Bottoms",
    "Sadiq Khan",
    "Anne Hidalgo",
    "Ada Colau",
    "Virginia Raggi",
    "Femke Halsema",
    "Boris Johnson",
    "David Cameron",
    "Tony Blair",
    "Gordon Brown",
    "John Major",
    "Nicolas Sarkozy",
    "François Hollande",
    "Marine Le Pen",
    "Jean-Luc Mélenchon",
    "Angela Merkel",
    "Gerhard Schröder",
    "Helmut Kohl",
    "Olaf Scholz",
    "Annalena Baerbock",
    "Robert Habeck",
    "Silvio Berlusconi",
    "Matteo Salvini",
    "Giuseppe Conte",
    "Mario Draghi",
    "Giorgia Meloni",
    "Pedro Sánchez",
    "Pablo Iglesias",
    "Mariano Rajoy",
    "José Luis Rodríguez Zapatero",
    "Felipe González",
    "Vladimir Putin",
    "Dmitry Medvedev",
    "Boris Yeltsin",
    "Mikhail Gorbachev",
    "Alexei Navalny",
    "Xi Jinping",
    "Hu Jintao",
    "Jiang Zemin",
    "Li Keqiang",
    "Deng Xiaoping",
    "Shinzo Abe",
    "Yoshihide Suga",
    "Fumio Kishida",
    "Junichiro Koizumi",
    "Yasuhiro Nakasone",
    "Moon Jae-in",
    "Park Geun-hye",
    "Lee Myung-bak",
    "Roh Moo-hyun",
    "Kim Dae-jung",
    "Narendra Modi",
    "Manmohan Singh",
    "Sonia Gandhi",
    "Rahul Gandhi",
    "Atal Bihari Vajpayee",
    "Imran Khan",
    "Benazir Bhutto",
    "Pervez Musharraf",
    "Nawaz Sharif",
    "Asif Ali Zardari",
    "Benjamin Netanyahu",
    "Ehud Olmert",
    "Ariel Sharon",
    "Shimon Peres",
    "Yitzhak Rabin",
    "Mahmoud Abbas",
    "Yasser Arafat",
    "King Abdullah II",
    "King Mohammed VI",
    "Recep Tayyip Erdogan",
    "Bashar al-Assad",
    "Muammar Gaddafi",
    "Hosni Mubarak",
    "Mohamed Morsi",
    "Abdel Fattah el-Sisi",
    "Nelson Mandela",
    "Thabo Mbeki",
    "Jacob Zuma",
    "Cyril Ramaphosa",
    "Desmond Tutu",
    "Robert Mugabe",
    "Uhuru Kenyatta",
    "Yoweri Museveni",
    "Paul Kagame",
    "Ellen Johnson Sirleaf",
    "Abiy Ahmed",
    "Haile Selassie",
    "Kofi Annan",
    "Boutros Boutros-Ghali",
    "Ban Ki-moon",
    "António Guterres",
    "Javier Solana",
    "Federica Mogherini",
    "Joseph Borrell",
    "Jens Stoltenberg",
    "Anders Fogh Rasmussen",
    "Jean-Claude Juncker",
    "Ursula von der Leyen",
    "Donald Tusk",
    "Herman Van Rompuy",
    "Christine Lagarde",
    "Dominique Strauss-Kahn",
    "Pascal Lamy",
    "Roberto Azevêdo",
    "Ngozi Okonjo-Iweala",
    "Jim Yong Kim",
    "David Malpass",
    "Kristalina Georgieva",
    "Tedros Adhanom",
    "Margaret Chan",
    "Gro Harlem Brundtland",
    "Irina Bokova",
    "Audrey Azoulay",
    "António Vitorino",
    "William Lacy Swing",
    "Filippo Grandi",
    "António Guterres",
    "Michelle Bachelet",
    "Zeid Raad Al Hussein",
    "Navi Pillay",
    "Mary Robinson",
    "Louise Arbour",
    "Fatou Bensouda",
    "Luis Moreno Ocampo",
    "Karim Khan",
    "Thomas Bach",
    "Jacques Rogge",
    "Juan Antonio Samaranch",
    "Sepp Blatter",
    "Gianni Infantino",
    "Michel Platini",
    "Aleksander Čeferin",
    "Adam Silver",
    "Roger Goodell",
    "Rob Manfred",
    "Gary Bettman",
    "Caster Semenya",
    "Megan Rapinoe",
    "Colin Kaepernick",
    "LeBron James",
    "Naomi Osaka",
    "Simone Biles",
    "Michael Phelps",
    "Usain Bolt",
    "Serena Williams",
    "Venus Williams",
    "Roger Federer",
    "Rafael Nadal",
    "Novak Djokovic",
    "Maria Sharapova",
    "Tiger Woods",
    "Rory McIlroy",
    "Phil Mickelson",
    "Annika Sörenstam",
    "Lindsey Vonn",
    "Shaun White",
    "Tony Hawk",
    "Kelly Slater",
    "Laird Hamilton",
    "Bethany Hamilton",
    "Michael Jordan",
    "Kobe Bryant",
    "Shaquille O'Neal",
    "Tim Duncan",
    "Dirk Nowitzki",
    "Stephen Curry",
    "Kevin Durant",
    "James Harden",
    "Russell Westbrook",
    "Giannis Antetokounmpo",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Neymar",
    "Kylian Mbappé",
    "Erling Haaland",
    "Pelé",
    "Diego Maradona",
    "Zinedine Zidane",
    "Ronaldinho",
    "Thierry Henry",
    "Wayne Rooney",
    "David Beckham",
    "Steven Gerrard",
    "Frank Lampard",
    "John Terry",
    "Didier Drogba",
    "Samuel Eto'o",
    "Yaya Touré",
    "Mohamed Salah",
    "Sadio Mané",
    "Riyad Mahrez",
    "Pierre-Emerick Aubameyang",
    "Karim Benzema",
    "Robert Lewandowski",
    "Thomas Müller",
    "Manuel Neuer",
    "Gianluigi Buffon",
    "Iker Casillas",
    "Petr Čech",
    "Edwin van der Sar",
    "Paolo Maldini",
    "Fabio Cannavaro",
    "Carles Puyol",
    "Sergio Ramos",
    "Gerard Piqué",
    "Xavi",
    "Andrés Iniesta",
    "Luka Modrić",
    "Toni Kroos",
    "Kevin De Bruyne",
    "Paul Pogba",
    "N'Golo Kanté",
    "Virgil van Dijk",
    "Ruud Gullit",
    "Marco van Basten",
    "Dennis Bergkamp",
    "Patrick Kluivert",
    "Arjen Robben",
    "Robin van Persie",
    "Wesley Sneijder",
    "Gareth Bale",
    "Harry Kane",
    "Raheem Sterling",
    "Marcus Rashford",
    "Jadon Sancho",
    "Phil Foden",
    "Mason Mount",
    "Trent Alexander-Arnold",
    "Bukayo Saka",
    "Jude Bellingham",
    "Erling Haaland",
    "Kylian Mbappé",
    "Joao Felix",
    "Ansu Fati",
    "Pedri",
    "Gavi",
    "Alphonso Davies",
    "Jamal Musiala",
    "Eduardo Camavinga",
    "Jude Bellingham",
    "Florian Wirtz",
    "Giovanni Reyna",
    "Youssoufa Moukoko",
    "Harvey Elliott",
    "Curtis Jones",
    "Takefusa Kubo",
    "Rodrygo",
    "Vinícius Júnior",
    "Gabriel Martinelli",
    "Emile Smith Rowe",
    "Dominic Calvert-Lewin",
    "Declan Rice",
    "Mason Greenwood",
    "Callum Hudson-Odoi",
    "Reece James",
    "Aaron Wan-Bissaka",
    "Ben Chilwell",
    "Dean Henderson",
    "Fikayo Tomori",
    "Tammy Abraham",
    "Ferran Torres",
    "Eric García",
    "Pau Torres",
    "Ansu Fati",
    "Pedri",
]

common_nouns = [
    "swivel chairs",
    "lampshades",
    "coffee tables",
    "window blinds",
    "throw pillows",
    "bookshelves",
    "wall clocks",
    "computer mice",
    "keyboard trays",
    "file cabinets",
    "desk lamps",
    "office plants",
    "whiteboard markers",
    "sticky notes",
    "water coolers",
    "paper shredders",
    "staplers",
    "hole punches",
    "pencil sharpeners",
    "thumb tacks",
    "bulletin boards",
    "desk calendars",
    "name plates",
    "business cards",
    "laptop stands",
    "power strips",
    "phone chargers",
    "headphone stands",
    "cable organizers",
    "mouse pads",
    "wrist rests",
    "monitor stands",
    "desk drawers",
    "trash cans",
    "recycling bins",
    "air purifiers",
    "space heaters",
    "desk fans",
    "foot rests",
    "desk pads",
    "coaster sets",
    "pen holders",
    "magazine racks",
    "letter trays",
    "paper clip holders",
    "tape dispensers",
    "document holders",
    "reading glasses",
    "desk mirrors",
    "desk plants",
    "motivational posters",
    "wall arts",
    "photo frames",
    "desk organizers",
    "cable clips",
    "laptop sleeves",
    "charging stations",
    "standing desks",
    "ergonomic chairs",
    "lumbar supports",
    "anti-fatigue mats",
    "monitor arms",
    "desk risers",
    "task lights",
    "floor lamps",
    "table lamps",
    "ceiling lights",
    "pendant lights",
    "wall sconces",
    "track lightings",
    "recessed lightings",
    "chandeliers",
    "floor fans",
    "ceiling fans",
    "tower fans",
    "window fans",
    "air conditioners",
    "humidifiers",
    "dehumidifiers",
    "vacuum cleaners",
    "handheld vacuums",
    "robot vacuums",
    "steam mops",
    "carpet cleaners",
    "window cleaners",
    "dusters",
    "brooms",
    "dustpans",
    "mop buckets",
    "trash bags",
    "cleaning wipes",
    "all-purpose cleaners",
    "glass cleaners",
    "furniture polishes",
    "laundry baskets",
    "clothes hangers",
    "garment racks",
    "shoe racks",
    "coat racks",
    "storage bins",
    "storage boxes",
    "under-bed storages",
    "closet organizers",
    "drawer dividers",
    "spice racks",
    "knife blocks",
    "cutting boards",
    "mixing bowls",
    "measuring cups",
    "kitchen scales",
    "food processors",
    "blenders",
    "stand mixers",
    "hand mixers",
    "toaster ovens",
    "microwaves",
    "coffee makers",
    "electric kettles",
    "slow cookers",
    "pressure cookers",
    "air fryers",
    "rice cookers",
    "waffle makers",
    "sandwich presses",
    "dish drying racks",
    "sink caddies",
    "paper towel holders",
    "utensil holders",
    "pot racks",
    "fruit bowls",
    "bread boxes",
    "cookie jars",
    "tea caddies",
    "wine racks",
    "bottle openers",
    "can openers",
    "vegetable peelers",
    "garlic presses",
    "cheese graters",
    "salad spinners",
    "colanders",
    "strainers",
    "ice cube trays",
    "oven mitts",
    "dish towels",
    "napkin holders",
    "place mats",
    "table runners",
    "serving trays",
    "dinner plates",
    "salad plates",
    "soup bowls",
    "coffee mugs",
    "wine glasses",
    "water glasses",
    "cutlery sets",
    "serving spoons",
    "ladles",
    "spatulas",
    "whisks",
    "tongs",
    "pizza cutters",
    "ice cream scoops",
    "potato mashers",
    "rolling pins",
    "pastry brushes",
    "meat thermometers",
    "kitchen timers",
    "oven racks",
    "baking sheets",
    "muffin tins",
    "loaf pans",
    "cake pans",
    "pie dishes",
    "casserole dishes",
    "roasting pans",
    "grill pans",
    "frying pans",
    "saucepans",
    "stock pots",
    "Dutch ovens",
    "woks",
    "steamer baskets",
    "coffee grinders",
    "tea infusers",
    "espresso machines",
    "milk frothers",
    "juicers",
    "food dehydrators",
    "egg poachers",
    "pancake griddles",
    "fondue sets",
    "sushi mats",
    "pasta makers",
    "spiralizers",
    "mandoline slicers",
    "mortars and pestles",
    "spice grinders",
    "pepper mills",
    "salt shakers",
    "oil dispensers",
    "vinegar cruets",
    "gravy boats",
    "butter dishes",
    "sugar bowls",
    "creamer pitchers",
    "teapots",
    "French presses",
    "coffee carafes",
    "water pitchers",
    "ice buckets",
    "cocktail shakers",
    "wine decanters",
    "corkscrews",
    "bottle stoppers",
    "coasters",
    "trivets",
    "pot holders",
    "aprons",
    "chef's hats",
    "kitchen scales",
    "recipe boxes",
    "cookbook stands",
    "spoon rests",
    "utensil crocks",
    "knife sharpeners",
    "cutting board oils",
    "dish soap dispensers",
    "sponge holders",
    "drain stoppers",
    "garbage disposals",
    "water filters",
    "refrigerators",
    "freezers",
    "dishwashers",
    "range hoods",
    "stovetops",
    "ovens",
    "toasters",
    "electric grills",
    "wine coolers",
    "kegerators",
    "ice makers",
    "trash compactors",
    "kitchen islands",
    "bar stools",
    "dining chairs",
    "dining tables",
    "sideboards",
    "china cabinets",
    "kitchen carts",
    "spice carousels",
    "lazy Susans",
    "cookbook shelves",
    "menu boards",
    "chalkboards",
    "magnetic knife strips",
    "paper towel holders",
    "kitchen clocks",
    "recipe holders",
    "kitchen rugs",
    "floor mats",
    "cabinet handles",
    "drawer pulls",
    "cabinet organizers",
    "pantry shelves",
    "can organizers",
    "jar openers",
    "egg slicers",
    "avocado slicers",
    "pineapple corers",
    "cherry pitters",
    "apple corers",
    "melon ballers",
    "citrus zesters",
    "herb scissors",
    "pizza stones",
    "meat tenderizers",
    "burger presses",
    "taco holders",
    "tortilla warmers",
    "chip clips",
    "food storage containers",
    "travel mugs",
    "thermoses",
    "lunch boxes",
    "picnic baskets",
    "coolers",
    "ice packs",
    "water bottles",
    "travel cutleries",
    "bento boxes",
    "food vacuum sealers",
    "canning jars",
    "fermenting crocks",
    "kombucha brewing kits",
    "beer brewing kits",
    "wine making kits",
    "cheese making kits",
    "yogurt makers",
    "bread machines",
    "pasta drying racks",
    "dumpling makers",
    "egg cookers",
    "bacon presses",
    "waffle cone makers",
    "cotton candy machines",
    "popcorn makers",
    "snow cone machines",
    "chocolate fountains",
    "electric wine openers",
    "beer growlers",
    "keg taps",
    "cocktail muddlers",
    "bar spoons",
    "jiggers",
    "shot glasses",
    "margarita glasses",
    "martini glasses",
    "champagne flutes",
    "beer steins",
    "whiskey decanters",
    "absinthe fountains",
    "cocktail umbrellas",
    "drink coasters",
    "bar towels",
    "napkin dispensers",
    "menu holders",
    "table number stands",
    "candle holders",
    "salt and pepper grinders",
    "bread baskets",
    "chip and dip sets",
    "cheese boards",
    "cake stands",
    "tiered serving trays",
    "punch bowls",
    "soup tureens",
    "carving boards",
    "carving knives",
    "meat forks",
    "barbecue grills",
    "grill tools",
    "grill covers",
    "charcoal chimneys",
    "smoker boxes",
    "rotisserie attachments",
    "grill baskets",
    "grill mats",
    "grill lights",
    "outdoor pizza ovens",
    "patio heaters",
    "mosquito zappers",
    "citronella candles",
    "tiki torches",
    "garden hoses",
    "watering cans",
    "plant pots",
    "window boxes",
    "herb planters",
    "garden trowels",
    "pruning shears",
    "gardening gloves",
    "kneeling pads",
    "wheelbarrows",
    "leaf blowers",
    "hedge trimmers",
    "lawn mowers",
    "weed whackers",
    "garden gnomes",
    "bird feeders",
    "bird baths",
    "squirrel feeders",
    "butterfly houses",
    "bee hotels",
    "rain gauges",
    "weather vanes",
    "sundials",
    "wind chimes",
    "garden statuaries",
    "patio umbrellas",
    "outdoor rugs",
    "hammocks",
    "porch swings",
    "adirondack chairs",
    "picnic tables",
    "fire pits",
    "outdoor string lights",
    "solar lanterns",
    "citronella torches",
    "outdoor speakers",
    "inflatable pools",
    "pool floats",
    "beach umbrellas",
    "beach towels",
    "coolers",
    "folding chairs",
    "camping tents",
    "sleeping bags",
    "flashlights",
    "binoculars",
    "compasses",
    "hiking boots",
    "backpacks",
    "water bottles",
    "first aid kits",
    "multi-tools",
    "camping stoves",
    "fishing rods",
    "tackle boxes",
    "kayaks",
    "canoes",
    "paddle boards",
    "life jackets",
    "wetsuits",
    "snorkel gears",
    "surfboards",
    "boogie boards",
    "beach balls",
    "frisbees",
    "kites",
    "badminton sets",
    "croquet sets",
    "bocce ball sets",
    "horseshoes",
    "cornhole games",
    "giant jengas",
    "outdoor chess sets",
    "ping pong tables",
    "foosball tables",
    "pool tables",
    "dart boards",
    "putting greens",
    "basketball hoops",
    "soccer goals",
    "volleyball nets",
    "trampolines",
    "swing sets",
    "slides",
    "seesaws",
    "sandboxes",
    "playhouses",
    "treehouses",
    "jungle gyms",
    "monkey bars",
    "balance beams",
    "climbing walls",
    "zip lines",
    "obstacle courses",
    "skate ramps",
]
